<?php
declare(strict_types=1);

namespace CharlesRothDotNet\Alfred;

use CharlesRothDotNet\Alfred\Str;

class MichiganCounty {

   public static function getId(string $name): int {
      if (empty($name))     return 0;
      $name = trim(strtoupper($name));
      $name = Str::replaceAll($name, ".", "");
      return self::$nameToId[$name] ?? 0;
   }

   public static function getName(int $id): string  {
      if ($id < 1  ||  $id > 83)  return "";
      return self::$idToName[$id];
   }

   private static array $nameToId = [
      "ALCONA" =>   1,
      "ALGER" =>   2,
      "ALLEGAN" =>   3,
      "ALPENA" =>   4,
      "ANTRIM" =>   5,
      "ARENAC" =>   6,
      "BARAGA" =>   7,
      "BARRY" =>   8,
      "BAY" =>   9,
      "BENZIE" =>  10,
      "BERRIEN" =>  11,
      "BRANCH" =>  12,
      "CALHOUN" =>  13,
      "CASS" =>  14,
      "CHARLEVOIX" =>  15,
      "CHEBOYGAN" =>  16,
      "CHIPPEWA" =>  17,
      "CLARE" =>  18,
      "CLINTON" =>  19,
      "CRAWFORD" =>  20,
      "DELTA" =>  21,
      "DICKINSON" =>  22,
      "EATON" =>  23,
      "EMMET" =>  24,
      "GENESEE" =>  25,
      "GLADWIN" =>  26,
      "GOGEBIC" =>  27,
      "GRAND TRAVERSE" =>  28,
      "GRATIOT" =>  29,
      "HILLSDALE" =>  30,
      "HOUGHTON" =>  31,
      "HURON" =>  32,
      "INGHAM" =>  33,
      "IONIA" =>  34,
      "IOSCO" =>  35,
      "IRON" =>  36,
      "ISABELLA" =>  37,
      "JACKSON" =>  38,
      "KALAMAZOO" =>  39,
      "KALKASKA" =>  40,
      "KENT" =>  41,
      "KEWEENAW" =>  42,
      "LAKE" =>  43,
      "LAPEER" =>  44,
      "LEELANAU" =>  45,
      "LENAWEE" =>  46,
      "LIVINGSTON" =>  47,
      "LUCE" =>  48,
      "MACKINAC" =>  49,
      "MACOMB" =>  50,
      "MANISTEE" =>  51,
      "MARQUETTE" =>  52,
      "MASON" =>  53,
      "MECOSTA" =>  54,
      "MENOMINEE" =>  55,
      "MIDLAND" =>  56,
      "MISSAUKEE" =>  57,
      "MONROE" =>  58,
      "MONTCALM" =>  59,
      "MONTMORENCY" =>  60,
      "MUSKEGON" =>  61,
      "NEWAYGO" =>  62,
      "OAKLAND" =>  63,
      "OCEANA" =>  64,
      "OGEMAW" =>  65,
      "ONTONAGON" =>  66,
      "OSCEOLA" =>  67,
      "OSCODA" =>  68,
      "OTSEGO" =>  69,
      "OTTAWA" =>  70,
      "PRESQUE ISLE" =>  71,
      "ROSCOMMON" =>  72,
      "SAGINAW" =>  73,
      "ST CLAIR" =>  74,
      "ST JOSEPH" =>  75,
      "SANILAC" =>  76,
      "SCHOOLCRAFT" =>  77,
      "SHIAWASSEE" =>  78,
      "TUSCOLA" =>  79,
      "VAN BUREN" =>  80,
      "WASHTENAW" =>  81,
      "WAYNE" =>  82,
      "WEXFORD" =>  83
   ];

   private static array $idToName = [
      1 =>  "ALCONA" ,
      2 =>  "ALGER" ,
      3 =>  "ALLEGAN" ,
      4 =>  "ALPENA" ,
      5 =>  "ANTRIM" ,
      6 =>  "ARENAC" ,
      7 =>  "BARAGA" ,
      8 =>  "BARRY" ,
      9 =>  "BAY" ,
      10 =>  "BENZIE" ,
      11 =>  "BERRIEN" ,
      12 =>  "BRANCH" ,
      13 =>  "CALHOUN" ,
      14 =>  "CASS" ,
      15 =>  "CHARLEVOIX" ,
      16 =>  "CHEBOYGAN" ,
      17 =>  "CHIPPEWA" ,
      18 =>  "CLARE" ,
      19 =>  "CLINTON" ,
      20 =>  "CRAWFORD" ,
      21 =>  "DELTA" ,
      22 =>  "DICKINSON" ,
      23 =>  "EATON" ,
      24 =>  "EMMET" ,
      25 =>  "GENESEE" ,
      26 =>  "GLADWIN" ,
      27 =>  "GOGEBIC" ,
      28 =>  "GRAND TRAVERSE" ,
      29 =>  "GRATIOT" ,
      30 =>  "HILLSDALE" ,
      31 =>  "HOUGHTON" ,
      32 =>  "HURON" ,
      33 =>  "INGHAM" ,
      34 =>  "IONIA" ,
      35 =>  "IOSCO" ,
      36 =>  "IRON" ,
      37 =>  "ISABELLA" ,
      38 =>  "JACKSON" ,
      39 =>  "KALAMAZOO" ,
      40 =>  "KALKASKA" ,
      41 =>  "KENT" ,
      42 =>  "KEWEENAW" ,
      43 =>  "LAKE" ,
      44 =>  "LAPEER" ,
      45 =>  "LEELANAU" ,
      46 =>  "LENAWEE" ,
      47 =>  "LIVINGSTON" ,
      48 =>  "LUCE" ,
      49 =>  "MACKINAC" ,
      50 =>  "MACOMB" ,
      51 =>  "MANISTEE" ,
      52 =>  "MARQUETTE" ,
      53 =>  "MASON" ,
      54 =>  "MECOSTA" ,
      55 =>  "MENOMINEE" ,
      56 =>  "MIDLAND" ,
      57 =>  "MISSAUKEE" ,
      58 =>  "MONROE" ,
      59 =>  "MONTCALM" ,
      60 =>  "MONTMORENCY" ,
      61 =>  "MUSKEGON" ,
      62 =>  "NEWAYGO" ,
      63 =>  "OAKLAND" ,
      64 =>  "OCEANA" ,
      65 =>  "OGEMAW" ,
      66 =>  "ONTONAGON" ,
      67 =>  "OSCEOLA" ,
      68 =>  "OSCODA" ,
      69 =>  "OTSEGO" ,
      70 =>  "OTTAWA" ,
      71 =>  "PRESQUE ISLE" ,
      72 =>  "ROSCOMMON" ,
      73 =>  "SAGINAW" ,
      74 =>  "ST CLAIR" ,
      75 =>  "ST JOSEPH" ,
      76 =>  "SANILAC" ,
      77 =>  "SCHOOLCRAFT" ,
      78 =>  "SHIAWASSEE" ,
      79 =>  "TUSCOLA" ,
      80 =>  "VAN BUREN" ,
      81 =>  "WASHTENAW" ,
      82 =>  "WAYNE" ,
   ];


}